import { sdk } from './sdk'

/**
 * The port the Burn After Reading server listens on inside its container.
 * The upstream binary defaults to 80 (overridable via a PORT env var).
 */
export const uiPort = 80

/** Where the service's data volume is mounted in the container. The binary
 * uses its working directory for everything: start9/config.yaml (config),
 * start9/stats.yaml, burn-after-reading.db (sled), big/ and tmp/. The image
 * sets WORKDIR to this mountpoint. */
export const dataDir = '/root'

/** Spec for the random BAR password, generated by the SDK on install. */
export const randomPassword = {
  charset: 'a-z,A-Z,0-9',
  len: 24,
}

export const mounts = sdk.Mounts.of().mountVolume({
  volumeId: 'main',
  subpath: null,
  mountpoint: dataDir,
  readonly: false,
})
